### ISSUE TITLE
`changeset` returning blank hash on nil to non-nil change

### ISSUE THREAD

**Issue by DLawla** [paper-trail-gem/paper_trail#1364]
Thank you for your contribution!

Using paper_trail 12.1.0, I have encounted an issue with the default `PaperTrail::Serializers::YAML`. I appears that if the `object_changes` column reflects a value changing from nil to a non-nil value, it raises an exception, and bubbles up to result in the `changeset` method returning an empty hash.

### Dependencies
ruby "3.1.0"
paper_trail (12.1.0)

### To recreate

Works as expected
```
object_changes = "---\nfirst_name:\n- Dan\n- Daniel\n"
PaperTrail::Serializers::YAML.load(object_changes)
 => {"first_name"=>["Dan", "Daniel"]} 
```

With a timestamp with an initial blank value, it raises an exception
```
object_changes = "---\npublished_at:\n-\n- 2022-01-09 19:51:23.668138000 Z\n" 
PaperTrail::Serializers::YAML.load(object_changes)

Exception raised: 
.../.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Time (Psych::DisallowedClass)
```

If there is anything else I can help provide, I'm happy to help!

**Comment by jaredbeck** [comment]
Hi Dan, Are you reporting a bug? If so, please use the [template](https://github.com/paper-trail-gem/paper_trail/blob/master/.github/ISSUE_TEMPLATE/bug-report.md)

**Comment by dsantosmerino** [comment]
Hey @DLawla, I think the error you found is related to #1338. Ruby 3.1 brings Psych 4.0, which has some [incompatibilities](https://bugs.ruby-lang.org/issues/17866) with previous versions. Have you tried using the `paper_trail` unreleased version?

```ruby
# Gemfile

gem "paper_trail", git: "https://github.com/paper-trail-gem/paper_trail"
```

**Comment by DLawla** [comment]
@jaredbeck Sorry about not using the template, thanks for the reminder!
@dsantosmerino Thanks, you're spot on. I can verify that the issue is fixed on master. I'll hold tight until another release is cut. Cheers!

**Comment by dcrec1** [comment]
Is this supposed to required that this config if `true`?

https://guides.rubyonrails.org/configuring.html#config-active-record-use-yaml-unsafe-load

Because when not being specified, the error persists in master.

**Comment by joshfester** [comment]
@dcrec1 setting that config to `true` fixed this issue for me. Using v13.0 with Ruby 3.1 and Rails 7

**Comment by activeliang** [comment]
# config/application.rb
``` 
    config.active_record.yaml_column_permitted_classes = [Symbol, Time]
```

**Comment by galievruslan** [comment]
I encountered the same problem
Rails 7.1.5
paper_trail 16.0.0

```
config.active_record.use_yaml_unsafe_load = true
```
Adding this config in a file application.rb fix problem
